### ISSUE TITLE
Hardcore Support

### ISSUE THREAD

**Issue by Lexiebean** [CosminPOP/LFT#11]
Could support for Hardcore mode be added?

You can check the player's spellbook to see if they're HC mode with something like:

```lua
local function ishc()
	local i = 1
	while true do
	local spellName, spellRank = GetSpellName(i, BOOKTYPE_SPELL)
		if not spellName then
			do break end
		end
		if spellName == "Hardcore" and spellRank == "Challenge" then
			return true
		end
     		i = i + 1
	end
end
```

Then maybe add a :hc:level to the end of your string to something so the group can members can be matched with hc only and people within +-5 levels of everyone else in the group.

**Comment by burner1024** [comment]
or just use another channel for HC chars

**Comment by Mosch0512** [comment]
This would be great

**Comment by Phobos-Programmer** [comment]
any update?

**Comment by Phobos-Programmer** [comment]
https://github.com/CosminPOP/LFT/pull/16

**Comment by Mosch0512** [comment]
@CosminPOP could you pls exlpain why #16 was not merged? Was something wrong? Can we fix it?
