### ISSUE TITLE
LFT window freezes

### ISSUE THREAD

**Issue by Gurky-Turtle** [CosminPOP/LFT#15]
![image](https://user-images.githubusercontent.com/90982783/221038669-c26bdff3-31ff-4eaf-922c-cc2ae2eec026.png)

Sometimes it happens that there is no way to close this window, which should close on its own. And have to restart the game, but after the restart the problem may occur again, this happens in 10% of cases. Can you add to the addon function that will close this frame, when the buttons wayting and leave are not clickable.

From here: https://github.com/slowtorta/turtlewow-bug-tracker/issues/2885 by @4iloveg

**Comment by CosminPOP** [comment]
![image](https://user-images.githubusercontent.com/7255825/221116700-5daee23a-1cc6-46de-bc05-a044052d186e.png)
