### ISSUE TITLE
Leave queue when working on quest objectives

### ISSUE THREAD

**Issue by Nawakland** [CosminPOP/LFT#3]
- LFT v0.0.2.4rc
- Wow client 1.12.1 (Gb)
- Group of 2 players (didn't test alone)

When working on an objective quest ,for example "kill 8 murloc", for each murloc killed group leave queue automaticlly. Then we have to queue again.
So it isn't possible to waiting for a dungeon group when questing.
No problem for starting and ending a quest.

Best regards.

**Comment by CosminPOP** [comment]
Can't reproduce. 
Can you tell me the exact dungeon you were queued for and the mob that triggered leaving queue when killed ?

**Comment by Nawakland** [comment]
More investigation.


It's remove group from queue when killing something, not only quest's related.
- All addons disable
- 1st member of the group : Paladin lvl16 as tank role (alliance)
- 2nd member of the group : Warlock lvl16 as dps role (alliance)
- Both hardcore mode and diplomat
- Queue in all Available Dungeons -> Ragefire Chasm
