### ISSUE TITLE
LUA error everytime someone join LFT 

### ISSUE THREAD

**Issue by Nawakland** [CosminPOP/LFT#4]
- LFT v0.0.2.5rc

Everytime someone join LFT queue it throws a lua error. Maybe related to the browse view (always empty).

![LFT_lua_error](https://user-images.githubusercontent.com/56754835/98353552-b785b400-201f-11eb-936e-20058a03f9ae.png)

**Comment by CosminPOP** [comment]
I think its related to someone having an older version and queueing for a dungeon that's not available in your version( his has 'mara' and yours only has 'maraorange', 'marapurple', and 'maraprincess'), ill push 2.6 today that checks for that and doesnt throw this error.
