### ISSUE TITLE
When queuing for two roles, only one role is queued for

### ISSUE THREAD

**Issue by clungo** [CosminPOP/LFT#9]
Repro steps:
-Enable LFT channel visibility
-Queue as both tank and healer for a dungeon
-Check chat, you will only be searching LFG as one role

**Comment by CosminPOP** [comment]
It is not recommended to enable that channel in the first place and it will be auto hidden after a short period.
Tank, healer, and dps chat spam have different timings 
![image](https://user-images.githubusercontent.com/7255825/134119259-772913b5-f2cf-4e45-9e6f-6206560fb32f.png)

**Comment by clungo** [comment]
true, my bad
